from custom_libs.custom_cfg import Custom_command

token = [''] # Токен(ы) групп
owner_id = [] # Те, кто смогут писать /restart

u = Custom_command( # Как пример спам бота
    command='start',

    delay=0.33,
    delay_error=10.0,

    message_counter_limit=6,

    call_from_id=[514714577],
    group_id=[216431142],
    any=False,


    text=f'',
    text_mode=1,
    random_text=False,

    attachment=['photo514714577_457312763'],
    random_attachment=False,

    button_mode=0,
    mode1_button_colors=[1, 2, 3, 0],
    mode1_2_3_buttons_text=['123', '321', '4323', '1230']
)
