token = "" # Токен группы

call_command = "start" # Вызов бота при помощи команды. Использование: / и текст, которые Вы задали в скобках. Не работает с пробелом
call_from_id = "666" # ID человека, который будет вызывать бота

text_mode = "1" # Режим отправляемого текста. 1 - стандартный режим, 2 - режим построчно
random_text = "0" # Случайно отправляет текст из режима текста 2. 0 - выключен, 1 - включен
text = "" # Текст сообщения
attachment = "" # Отправляет любое из перечисленных вложений: 'photo' — фото, 'video' — видео, 'audio' — аудио, 'doc' — докумен, 'wall' — пост на стене. Формат подписи такой: <Вложение><Владелец этого вложения>_<id вложения>, пример: photo514714577_457311228
random_attachment = "0" # Случайно отправляет из вписанных вложений. 0 - выключен, 1 - включен

button_mode = "1" # Вид отправляемых кнопок. 1 - стандартный режим, 2 - режим радуги, 3 - режим вируса, 4 - режим остановки, 5 - режим из бота "sparta raid", 0 - выключить кнопки

mode1_4_button_color1 = "0" # Цвет кнопки 1 для режимов 1 и 4. 0 - зелёная, 1 - красная, 2 - синяя, 3 - серая
mode1_button_color2 = "1" # Цвет кнопки 2 для режима 1. 0 - зелёная, 1 - красная, 2 - синяя, 3 - серая
mode1_button_color3 = "2" # Цвет кнопки 3 для режима 1. 0 - зелёная, 1 - красная, 2 - синяя, 3 - серая
mode1_button_color4 = "3" # Цвет кнопки 4 для режима 1. 0 - зелёная, 1 - красная, 2 - синяя, 3 - серая

mode1_2_3_4_button_text1 = "Text1" # Текст кнопки 1 для режимов 1, 2, 3 и 4
mode1_2_3_button_text2 = "Text2" # Текст кнопки 2 для режимов 1, 2 и 3
mode1_2_3_button_text3 = "Text3" # Текст кнопки 3 для режимов 1, 2 и 3
mode1_2_3_button_text4 = "Text4" # Текст кнопки 4 для режимов 1, 2 и 3

mode_4_text = "Перестаю спамить" # Текст сообщения для режима 4

message_counter_limit = "-1" # Отправляет n-ое количество сообщений, а после перестаёт работать. Чтобы спамило бесконечно, нужно ставить отрицательные числа (-1 к примеру)

delay = "1.0" # Задержка перед отправкой следующего сообщения
delay_kill = "10.0" # Задержка перед отправкой следующего сообщения после ошибки
delay_stop = "60.0" # Задержка после нажатия кнопки в режиме 4
