token = "vk1.a.y6AYcUguoPrQBA7p3jXB-CsgV179hsxC1s_r3hwlT7zdO1zNB8MunuO7J2TGwkKpZ-eIeyB9INIMG5LB5bmaDMq9qpdoM23zekTW6S0Bja2GilbSjKtuWzhqD6eVjCWnEAN7OvE_Gdx-iXXcFx0OJIvvHC_OIwNf_SsshKw6w1LRTT3H9iDWegQDPMBQltr6" # Токен группы

call_command = "start" # Вызов бота при помощи команды. Использование: / и текст, которые Вы задали в скобках. Не работает с пробелом
call_from_id = "" # ID человека, который будет вызывать бота

text = "👹" # Текст сообщения
attachment = "" # Отправляет любое из перечисленных вложений: 'photo' — фото, 'video' — видео, 'audio' — аудио, 'doc' — докумен, 'wall' — пост на стене. Формат подписи такой: <Вложение><Владелец этого вложения>_<id вложения>, пример: photo514714577_457311228

button_mode = "1" # Вид отправляемых кнопок. Пока тут только один режим, добавляться будут в следующих обновлениях. Любая другая цифра не в списке - выключение кнопок. 1 - стандартный

mode1_button_color1 = "0" # Цвет кнопки 1 для режима 1. 0 - зелёная, 1 - красная, 2 - синяя, 3 - серая
mode1_button_color2 = "1" # Цвет кнопки 2 для режима 1. 0 - зелёная, 1 - красная, 2 - синяя, 3 - серая
mode1_button_color3 = "2" # Цвет кнопки 3 для режима 1. 0 - зелёная, 1 - красная, 2 - синяя, 3 - серая
mode1_button_color4 = "3" # Цвет кнопки 4 для режима 1. 0 - зелёная, 1 - красная, 2 - синяя, 3 - серая

mode1_button_text1 = "Button" # Текст кнопки 1 для режима 1
mode1_button_text2 = "Button" # Текст кнопки 2 для режима 1
mode1_button_text3 = "Button" # Текст кнопки 3 для режима 1
mode1_button_text4 = "Button" # Текст кнопки 4 для режима 1

message_counter_limit = "-1" # Отправляет n-ое количество сообщений, а после перестаёт работать. Чтобы спамило бесконечно, нужно ставить отрицательные числа (-1 к примеру)

delay = "1.0" # Задержка перед отправкой следующего сообщения
delay_kill = "10.0" # Задержка перед отправкой следующего сообщения после ошибки